/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: 'var(--color-surface, #fcf8ff)',
        'surface-dim': 'var(--color-surface-dim, #dcd8e5)',
        'surface-bright': 'var(--color-surface-bright, #fcf8ff)',
        'surface-container-lowest': 'var(--color-surface-container-lowest, #ffffff)',
        'surface-container-low': 'var(--color-surface-container-low, #f5f2ff)',
        'surface-container': 'var(--color-surface-container, #f0ecf9)',
        'surface-container-high': 'var(--color-surface-container-high, #eae6f4)',
        'surface-container-highest': 'var(--color-surface-container-highest, #e4e1ee)',
        'on-surface': 'var(--color-on-surface, #1b1b24)',
        'on-surface-variant': 'var(--color-on-surface-variant, #464555)',
        'inverse-surface': 'var(--color-inverse-surface, #302f39)',
        'inverse-on-surface': 'var(--color-inverse-on-surface, #f3effc)',
        outline: 'var(--color-outline, #777587)',
        'outline-variant': 'var(--color-outline-variant, #c7c4d8)',
        'surface-tint': 'var(--color-surface-tint, #4d44e3)',
        primary: 'var(--color-primary, #3525cd)',
        'on-primary': 'var(--color-on-primary, #ffffff)',
        'primary-container': 'var(--color-primary-container, #4f46e5)',
        'on-primary-container': 'var(--color-on-primary-container, #dad7ff)',
        'inverse-primary': 'var(--color-inverse-primary, #c3c0ff)',
        secondary: 'var(--color-secondary, #505f76)',
        'on-secondary': 'var(--color-on-secondary, #ffffff)',
        'secondary-container': 'var(--color-secondary-container, #d0e1fb)',
        'on-secondary-container': 'var(--color-on-secondary-container, #54647a)',
        tertiary: 'var(--color-tertiary, #7e3000)',
        'on-tertiary': 'var(--color-on-tertiary, #ffffff)',
        'tertiary-container': 'var(--color-tertiary-container, #a44100)',
        'on-tertiary-container': 'var(--color-on-tertiary-container, #ffd2be)',
        error: 'var(--color-error, #ba1a1a)',
        'on-error': 'var(--color-on-error, #ffffff)',
        'error-container': 'var(--color-error-container, #ffdad6)',
        'on-error-container': 'var(--color-on-error-container, #93000a)',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        display: ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'mono-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
      },
      spacing: {
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '20px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      boxShadow: {
        'level-1': '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1)',
        'level-2': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
      },
    },
  },
  plugins: [],
};
